
# This file is automatically generated, you probably don't want to edit this

krippOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "krippOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            CID = NULL,
            CaID = NULL,
            vals = NULL,
            level = "nominal",
            rat = FALSE,
            cas = FALSE, ...) {

            super$initialize(
                package="InterRaterReliability",
                name="kripp",
                requiresData=TRUE,
                ...)

            private$..CID <- jmvcore::OptionVariable$new(
                "CID",
                CID,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "id"))
            private$..CaID <- jmvcore::OptionVariable$new(
                "CaID",
                CaID,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "id"))
            private$..vals <- jmvcore::OptionVariables$new(
                "vals",
                vals)
            private$..level <- jmvcore::OptionList$new(
                "level",
                level,
                options=list(
                    "nominal",
                    "ordinal",
                    "interval",
                    "ratio"),
                default="nominal")
            private$..rat <- jmvcore::OptionBool$new(
                "rat",
                rat,
                default=FALSE)
            private$..cas <- jmvcore::OptionBool$new(
                "cas",
                cas,
                default=FALSE)

            self$.addOption(private$..CID)
            self$.addOption(private$..CaID)
            self$.addOption(private$..vals)
            self$.addOption(private$..level)
            self$.addOption(private$..rat)
            self$.addOption(private$..cas)
        }),
    active = list(
        CID = function() private$..CID$value,
        CaID = function() private$..CaID$value,
        vals = function() private$..vals$value,
        level = function() private$..level$value,
        rat = function() private$..rat$value,
        cas = function() private$..cas$value),
    private = list(
        ..CID = NA,
        ..CaID = NA,
        ..vals = NA,
        ..level = NA,
        ..rat = NA,
        ..cas = NA)
)

krippResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "krippResults",
    inherit = jmvcore::Group,
    active = list(
        krippAlph = function() private$.items[["krippAlph"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Krippendorff's Alpha")
            self$add(jmvcore::Table$new(
                options=options,
                name="krippAlph",
                title="Krippendorff's Alpha",
                rows="(vals)",
                clearWith=list(
                    "CID",
                    "CaID",
                    "vals"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))}))

krippBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "krippBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "InterRaterReliability",
                name = "kripp",
                version = c(1,0,0),
                options = options,
                results = krippResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Krippendorff's Alpha
#'
#' 
#' @param data .
#' @param CID .
#' @param CaID .
#' @param vals .
#' @param level .
#' @param rat .
#' @param cas .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$krippAlph} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$krippAlph$asDF}
#'
#' \code{as.data.frame(results$krippAlph)}
#'
#' @export
kripp <- function(
    data,
    CID,
    CaID,
    vals,
    level = "nominal",
    rat = FALSE,
    cas = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("kripp requires jmvcore to be installed (restart may be required)")

    if ( ! missing(CID)) CID <- jmvcore::resolveQuo(jmvcore::enquo(CID))
    if ( ! missing(CaID)) CaID <- jmvcore::resolveQuo(jmvcore::enquo(CaID))
    if ( ! missing(vals)) vals <- jmvcore::resolveQuo(jmvcore::enquo(vals))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(CID), CID, NULL),
            `if`( ! missing(CaID), CaID, NULL),
            `if`( ! missing(vals), vals, NULL))


    options <- krippOptions$new(
        CID = CID,
        CaID = CaID,
        vals = vals,
        level = level,
        rat = rat,
        cas = cas)

    analysis <- krippClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

