
# This file is automatically generated, you probably don't want to edit this

percAgreeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "percAgreeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            CID = NULL,
            CaID = NULL,
            vals = NULL,
            percAgree = FALSE,
            hol = FALSE,
            naMethod = "pairwise",
            rat = FALSE,
            cas = FALSE, ...) {

            super$initialize(
                package="InterRaterReliability",
                name="percAgree",
                requiresData=TRUE,
                ...)

            private$..CID <- jmvcore::OptionVariable$new(
                "CID",
                CID,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "id"))
            private$..CaID <- jmvcore::OptionVariable$new(
                "CaID",
                CaID,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "id"))
            private$..vals <- jmvcore::OptionVariables$new(
                "vals",
                vals)
            private$..percAgree <- jmvcore::OptionBool$new(
                "percAgree",
                percAgree,
                default=FALSE)
            private$..hol <- jmvcore::OptionBool$new(
                "hol",
                hol,
                default=FALSE)
            private$..naMethod <- jmvcore::OptionList$new(
                "naMethod",
                naMethod,
                options=list(
                    "pairwise",
                    "listwise"),
                default="pairwise")
            private$..rat <- jmvcore::OptionBool$new(
                "rat",
                rat,
                default=FALSE)
            private$..cas <- jmvcore::OptionBool$new(
                "cas",
                cas,
                default=FALSE)

            self$.addOption(private$..CID)
            self$.addOption(private$..CaID)
            self$.addOption(private$..vals)
            self$.addOption(private$..percAgree)
            self$.addOption(private$..hol)
            self$.addOption(private$..naMethod)
            self$.addOption(private$..rat)
            self$.addOption(private$..cas)
        }),
    active = list(
        CID = function() private$..CID$value,
        CaID = function() private$..CaID$value,
        vals = function() private$..vals$value,
        percAgree = function() private$..percAgree$value,
        hol = function() private$..hol$value,
        naMethod = function() private$..naMethod$value,
        rat = function() private$..rat$value,
        cas = function() private$..cas$value),
    private = list(
        ..CID = NA,
        ..CaID = NA,
        ..vals = NA,
        ..percAgree = NA,
        ..hol = NA,
        ..naMethod = NA,
        ..rat = NA,
        ..cas = NA)
)

percAgreeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "percAgreeResults",
    inherit = jmvcore::Group,
    active = list(
        warning = function() private$.items[["warning"]],
        agree = function() private$.items[["agree"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="percent Agreement")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="warning",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="agree",
                title="Rater Agreement",
                rows="(vals)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="Raters", 
                        `title`="Raters", 
                        `type`="integer", 
                        `visible`="(rat)"),
                    list(
                        `name`="Cases", 
                        `title`="Cases", 
                        `type`="integer", 
                        `visible`="(cas)"),
                    list(
                        `name`="Agr", 
                        `title`="Agreement", 
                        `type`="integer", 
                        `visible`="(percAgree)"),
                    list(
                        `name`="Holsti", 
                        `title`="Holsti", 
                        `type`="integer", 
                        `visible`="(hol)", 
                        `format`="zto"))))}))

percAgreeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "percAgreeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "InterRaterReliability",
                name = "percAgree",
                version = c(1,0,0),
                options = options,
                results = percAgreeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Percent Agreement
#'
#' 
#' @param data .
#' @param CID .
#' @param CaID .
#' @param vals .
#' @param percAgree .
#' @param hol .
#' @param naMethod .
#' @param rat .
#' @param cas .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$warning} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$agree} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$agree$asDF}
#'
#' \code{as.data.frame(results$agree)}
#'
#' @export
percAgree <- function(
    data,
    CID,
    CaID,
    vals,
    percAgree = FALSE,
    hol = FALSE,
    naMethod = "pairwise",
    rat = FALSE,
    cas = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("percAgree requires jmvcore to be installed (restart may be required)")

    if ( ! missing(CID)) CID <- jmvcore::resolveQuo(jmvcore::enquo(CID))
    if ( ! missing(CaID)) CaID <- jmvcore::resolveQuo(jmvcore::enquo(CaID))
    if ( ! missing(vals)) vals <- jmvcore::resolveQuo(jmvcore::enquo(vals))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(CID), CID, NULL),
            `if`( ! missing(CaID), CaID, NULL),
            `if`( ! missing(vals), vals, NULL))


    options <- percAgreeOptions$new(
        CID = CID,
        CaID = CaID,
        vals = vals,
        percAgree = percAgree,
        hol = hol,
        naMethod = naMethod,
        rat = rat,
        cas = cas)

    analysis <- percAgreeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

